title: "[Idea] "
labels: ["enhancement", "idea"]
body:
  - type: markdown
    attributes:
      value: |
        ## Share Your Ideas

        Help improve the NexVigilant B-R Toolkit with your suggestions!

  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: What improvement or new feature would you like to see?
      placeholder: Describe your idea...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Module Content
        - New Template
        - New Notebook/Tutorial
        - Documentation Improvement
        - Visualization Enhancement
        - Accessibility
        - Other
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: How would this help learners?
      placeholder: Explain the value this would provide...
